version: '3.6'

services:
  database:
    image: postgres:13.4-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - 'POSTGRES_DB=${DB_DATABASE}'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
