name: main

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Lint API
        run: yarn lint

      - name: Build API
        run: yarn build

      - name: Test API
        run: yarn test

      - name: Build Client
        run: cd apps/web && yarn build

      - name: Lint Client
        run: cd apps/web && yarn lint
